/*
 * ChannelPreview.js
 *
 * PixInsight 1.9.4+ feature script (V8 runtime).
 *
 * One-shot generator of every common channel decomposition of the active
 * view. Useful for narrowband palette experimentation (which channel
 * carries the cleanest Ha vs OIII signal? which RGB combine assignment
 * gives the best a-star / b-star?) and for diagnosing broadband galaxy color casts.
 *
 * Generates (selectable):
 *   RGB                : R, G, B channels
 *   CIE L*a*b*         : L*, a*, b*
 *   CIE L*c*h*         : L*, c*, h*
 *   HSV                : H, S, V
 *   HSI                : H, S, I
 *   CIE XYZ            : X, Y, Z
 *   Inverted variants of all of the above (optional)
 *
 * Output windows are named "<sourceId>_<space>_<channel>". A contact-sheet
 * preview window may also be generated by tiling the produced channels.
 */
#engine v8
#feature-id  ChannelPreview : EGo > Channel Preview (all spaces)
#feature-info Generates every common channel decomposition (RGB, L*a*b*, \
   L*c*h*, HSV, HSI, XYZ) of the active view, optionally with inverted \
   variants and a tiled contact-sheet. Useful for narrowband palette \
   experimentation.

CoreApplication.ensureMinimumVersion( 1, 9, 4 );

#define VERSION "1.0.0"
#define TITLE   "Channel Preview"

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

function log( msg )  { console.writeln( "<end><cbr>* " + msg ); }
function warn( msg ) { console.warningln( "<end><cbr>** " + msg ); }

function uniqueId( base )
{
   let id = base;
   let n = 1;
   while ( !ImageWindow.windowById( id ).isNull )
   {
      id = base + "_" + n;
      ++n;
   }
   return id;
}

// Color space enumeration, plus channel labels for output naming.
const SPACES = [
   { key: "RGB",  cs: ColorSpace.RGB,  labels: [ "R", "G", "B" ] },
   { key: "Lab",  cs: ColorSpace.CIELab, labels: [ "L", "a", "b" ] },
   { key: "Lch",  cs: ColorSpace.CIEch, labels: [ "L", "c", "h" ] },
   { key: "HSV",  cs: ColorSpace.HSV,  labels: [ "H", "S", "V" ] },
   { key: "HSI",  cs: ColorSpace.HSI,  labels: [ "H", "S", "I" ] },
   { key: "XYZ",  cs: ColorSpace.CIEXYZ, labels: [ "X", "Y", "Z" ] }
];

// Extract channels via ChannelExtraction. Returns array of resulting view IDs.
function extractSpace( srcView, space, baseId )
{
   let CE = new ChannelExtraction;
   CE.colorSpace  = space.cs;
   CE.sampleFormat = ChannelExtraction.SameAsSource;
   // Each channel: [ enabled, optional name, sample format ]
   let names = space.labels.map( L => uniqueId( baseId + "_" + space.key + "_" + L ) );
   CE.channels = [
      [ true, names[0] ],
      [ true, names[1] ],
      [ true, names[2] ]
   ];
   if ( !CE.executeOn( srcView ) )
   {
      warn( space.key + " extraction failed." );
      return [];
   }
   log( "Extracted " + space.key + ": " + names.join( ", " ) );
   return names;
}

function invertView( view )
{
   let P = new PixelMath;
   P.expression = "~$T";
   P.useSingleExpression = true;
   P.createNewImage = false;
   P.rescale  = false;
   P.truncate = true;
   P.truncateLower = 0;
   P.truncateUpper = 1;
   P.executeOn( view );
}

// Generate a tiled contact sheet from a list of view IDs.
// Each tile is downsampled to fit `tileSize` px on the long edge.
function makeContactSheet( ids, baseId, tileSize, cols )
{
   if ( ids.length === 0 )
      return null;

   let tiles = [];
   let maxW = 0, maxH = 0;

   for ( let i = 0; i < ids.length; ++i )
   {
      let w = ImageWindow.windowById( ids[i] );
      if ( w.isNull ) continue;
      let img = w.mainView.image;
      let scale = tileSize / Math.max( img.width, img.height );
      let tw = Math.round( img.width  * scale );
      let th = Math.round( img.height * scale );
      tiles.push( { id: ids[i], w: tw, h: th } );
      if ( tw > maxW ) maxW = tw;
      if ( th > maxH ) maxH = th;
   }
   if ( tiles.length === 0 )
      return null;

   let rows = Math.ceil( tiles.length / cols );
   let pad = 8;
   let labelH = 18;
   let sheetW = cols * maxW + (cols + 1) * pad;
   let sheetH = rows * (maxH + labelH) + (rows + 1) * pad;

   let bmp = new Bitmap( sheetW, sheetH );
   bmp.fill( 0xff202020 );

   let G = new Graphics( bmp );
   G.antialiasing = true;
   G.pen   = new Pen( 0xffe0e0e0 );
   G.brush = new Brush( 0xffe0e0e0 );
   G.font  = new Font( "Helvetica", 9 );

   for ( let i = 0; i < tiles.length; ++i )
   {
      let r = Math.floor( i / cols );
      let c = i % cols;
      let x = pad + c * (maxW + pad);
      let y = pad + r * (maxH + labelH + pad);

      let w = ImageWindow.windowById( tiles[i].id );
      let srcImg = w.mainView.image;

      // Auto-stretch the tile so dim channels are visible.
      let tmpBmp = srcImg.render();
      let scaled = tmpBmp.scaledTo( tiles[i].w, tiles[i].h );
      tmpBmp.clear(); // explicit deallocation per V8 guidance

      G.drawBitmap( x, y + labelH, scaled );
      scaled.clear();

      G.drawText( x, y + labelH - 2, tiles[i].id );
   }
   G.end();

   let sheetId = uniqueId( baseId + "_contactSheet" );
   let win = new ImageWindow( sheetW, sheetH,
                              3,      // numberOfChannels
                              8,      // bitsPerSample
                              false,  // floatSample
                              true,   // color
                              sheetId );
   win.mainView.beginProcess( UndoFlag.NoSwapFile );
   win.mainView.image.blend( bmp );
   win.mainView.endProcess();
   win.show();
   win.zoomToFit();

   bmp.clear();
   log( "Created contact sheet: " + sheetId + "  (" + tiles.length + " tiles)" );
   return win;
}

// ---------------------------------------------------------------------------
// Dialog
// ---------------------------------------------------------------------------

var ChannelPreviewDialog = class extends Dialog
{
   constructor()
   {
      super();

      let self = this;
      this.windowTitle = TITLE + " " + VERSION;
      this.minWidth = 460;

      // Source view
      this.targetGroup = new GroupBox( this );
      this.targetGroup.title = "Source view (must be color)";
      this.targetCombo = new ViewList( this );
      this.targetCombo.getMainViews();
      let aw = ImageWindow.activeWindow;
      if ( !aw.isNull )
         this.targetCombo.currentView = aw.mainView;
      let tg = new VerticalSizer;
      tg.margin = 6; tg.spacing = 4;
      tg.add( this.targetCombo );
      this.targetGroup.sizer = tg;

      // Spaces
      this.spaceGroup = new GroupBox( this );
      this.spaceGroup.title = "Color spaces to extract";
      let sg = new VerticalSizer;
      sg.margin = 6; sg.spacing = 4;

      this.spaceChecks = {};
      let defOn = { RGB: true, Lab: true, Lch: false, HSV: false, HSI: true, XYZ: false };
      for ( let i = 0; i < SPACES.length; ++i )
      {
         let s = SPACES[i];
         let cb = new CheckBox( this );
         cb.text = s.key + "  (" + s.labels.join( ", " ) + ")";
         cb.checked = !!defOn[ s.key ];
         this.spaceChecks[ s.key ] = cb;
         sg.add( cb );
      }
      this.spaceGroup.sizer = sg;

      // Options
      this.optGroup = new GroupBox( this );
      this.optGroup.title = "Options";
      let og = new VerticalSizer;
      og.margin = 6; og.spacing = 4;

      this.cbInvert = new CheckBox( this );
      this.cbInvert.text = "Also generate inverted channels";
      this.cbInvert.checked = false;

      this.cbSheet = new CheckBox( this );
      this.cbSheet.text = "Generate tiled contact sheet";
      this.cbSheet.checked = true;

      this.tileSize = new NumericEdit( this );
      this.tileSize.label.text = "Contact-sheet tile size (px):";
      this.tileSize.setRange( 128, 1024 );
      this.tileSize.setPrecision( 0 );
      this.tileSize.setValue( 384 );

      this.cols = new NumericEdit( this );
      this.cols.label.text = "Contact-sheet columns:";
      this.cols.setRange( 1, 8 );
      this.cols.setPrecision( 0 );
      this.cols.setValue( 3 );

      og.add( this.cbInvert );
      og.add( this.cbSheet );
      og.add( this.tileSize );
      og.add( this.cols );
      this.optGroup.sizer = og;

      // Buttons
      this.okBtn = new PushButton( this );
      this.okBtn.text = "Generate";
      this.okBtn.icon = this.scaledResource( ":/icons/ok.png" );
      this.okBtn.onClick = function() { self.ok(); };

      this.cancelBtn = new PushButton( this );
      this.cancelBtn.text = "Cancel";
      this.cancelBtn.icon = this.scaledResource( ":/icons/cancel.png" );
      this.cancelBtn.onClick = function() { self.cancel(); };


      this.helpBtn = new ToolButton( this );

      this.helpBtn.icon = this.scaledResource( ":/process-interface/browse-documentation.png" );

      this.helpBtn.toolTip = "Browse documentation";

      this.helpBtn.onClick = function() {

         try {

            if ( !Dialog.browseScriptDocumentation( "ChannelPreview" ) )
               Dialog.openBrowser(
                  "file://" + CoreApplication.installationDirectory +
                  "/doc/scripts/ChannelPreview/ChannelPreview.html",
                  "ChannelPreview Documentation" );

         } catch ( e ) {

            console.warningln( "Could not open docs: " + e.message );

         }

      };


      let btnRow = new HorizontalSizer;
      btnRow.spacing = 6;

      btnRow.add( this.helpBtn );
      btnRow.addStretch();
      btnRow.add( this.okBtn );
      btnRow.add( this.cancelBtn );

      this.sizer = new VerticalSizer;
      this.sizer.margin = 8;
      this.sizer.spacing = 6;
      this.sizer.add( this.targetGroup );
      this.sizer.add( this.spaceGroup );
      this.sizer.add( this.optGroup );
      this.sizer.add( btnRow );
      this.adjustToContents();
   }
};

// ---------------------------------------------------------------------------
// Entry
// ---------------------------------------------------------------------------

(() =>
{
   let dlg = new ChannelPreviewDialog;
   if ( !dlg.execute() ) return;

   let v = dlg.targetCombo.currentView;
   if ( v.isNull )
   {
      (new MessageBox( "Please pick a source view.", TITLE, StdIcon.Warning )).execute();
      return;
   }
   if ( !v.image.isColor )
   {
      (new MessageBox( "Source view must be a color image.", TITLE, StdIcon.Warning )).execute();
      return;
   }

   console.show();
   console.writeln( "<end><cbr><br>=== " + TITLE + " " + VERSION + " ===" );
   log( "Source view: " + v.id );
   let E = new ElapsedTime;

   let baseId = v.id;
   let producedIds = [];

   for ( let i = 0; i < SPACES.length; ++i )
   {
      let s = SPACES[i];
      if ( !dlg.spaceChecks[ s.key ].checked )
         continue;

      let ids = extractSpace( v, s, baseId );
      producedIds = producedIds.concat( ids );

      if ( dlg.cbInvert.checked )
      {
         for ( let j = 0; j < ids.length; ++j )
         {
            let w = ImageWindow.windowById( ids[j] );
            if ( w.isNull ) continue;
            // Duplicate then invert so we keep the original.
            let src = w.mainView.image;
            let invId = uniqueId( ids[j] + "_inv" );
            let invWin = new ImageWindow(
               src.width, src.height, src.numberOfChannels,
               src.bitsPerSample, src.isReal, src.isColor, invId
            );
            invWin.mainView.beginProcess( UndoFlag.NoSwapFile );
            invWin.mainView.image.assign( src );
            invWin.mainView.endProcess();
            invertView( invWin.mainView );
            invWin.show();
            producedIds.push( invId );
            log( "Inverted: " + invId );
         }
      }
   }

   if ( dlg.cbSheet.checked && producedIds.length > 0 )
      makeContactSheet( producedIds, baseId, dlg.tileSize.value, dlg.cols.value );

   log( "Done in " + E.text + "  (" + producedIds.length + " channel images)" );
})();
